### ISSUE TITLE
kafka-connect-rest and confluent-5.0.0

### ISSUE THREAD

**Issue by martindupond** [llofberg/kafka-connect-rest#14]
Hello,
I would like to use kafka-connect-rest with confluent-5.0.0
After the following steps:
1- git clone https://github.com/llofberg/kafka-connect-rest.git
2- modifying pom.xml to have
<kafka.version>2.0.0</kafka.version>
<confluent.version>5.0.0</confluent.version>
3- mvn clean install
I got:
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/dupond/confluent-5.0.0/plugin/kafka-connect-rest/src/test/java/com/tm/kafka/connect/rest/RestTaskTest.java:[89,26] error: incompatible types: SourceTaskContext is not a functional interface
[ERROR]     multiple non-overriding abstract methods found in interface SourceTaskContext
/home/dupond/confluent-5.0.0/plugin/kafka-connect-rest/src/test/java/com/tm/kafka/connect/rest/RestTaskTest.java:[105,26] error: incompatible types: SourceTaskContext is not a functional interface
[ERROR]     multiple non-overriding abstract methods found in interface SourceTaskContext
/home/dupond/confluent-5.0.0/plugin/kafka-connect-rest/src/test/java/com/tm/kafka/connect/rest/RestTaskTest.java:[207,19] error: MockSinkTaskContext is not abstract and does not override abstract method configs() in SinkTaskContext
[INFO] 3 errors

configuration: Maven 3.5.4, Confluent 5.0.0, Debian 9, Java 1.8

Are there other basic modifications I could do to have this connector working?
Thank you
Martin

**Comment by llofberg** [comment]
I updated to Kafka v2 and Confluent v5.
Please also take a look at the transformations branch.
I will merge it to master soon.
