### ISSUE TITLE
Sending data from kafka topic to multiple endpoint URLs

### ISSUE THREAD

**Issue by Thalia-Long** [llofberg/kafka-connect-rest#6]
hey Lenny, 
I finally got this connector up and running. My problem before was the mis/match kafka version. I used 1.0.0 instead of 1.1.0. So upgrading to 1.1.0 solved my problem.
Could this connector send data to multiple endpoint URLs, or it can only send data to one URL?

**Comment by llofberg** [comment]
Thalia-Long

It might be better to run a separate connector for each URL.
Error handling might be simpler that way.

- lenny

**Comment by Thalia-Long** [comment]
Thanks for your response.
