### ISSUE TITLE
Running in distributed mode

### ISSUE THREAD

**Issue by justinjoseph89** [llofberg/kafka-connect-rest#9]
Hi @llofberg 

I am trying to run the connector in distributed mode , will this framework handle that for us in default or do we need to handle or implement anything inside the poll method ? From what i can see is when running in distributed mode with two tasks i can see my data is getting duplicated means each task is calling the URL .

Thanks,
Justin Joseph

**Comment by llofberg** [comment]
Justin

Kafka Connect should handle that automatically. Not sure the answer here would help.

https://stackoverflow.com/questions/41720037/kafka-connect-creating-a-new-connector-in-distributed-mode-is-creating-new-grou

- lenny
